server.port=8080
spring.application.name=customer-api

# swagger
springdoc.swagger-ui.path=/customer-api/swagger-ui.html

spring.data.mongodb.uri=mongodb+srv://marinaorzechowski:{***}@cluster0.pijey.mongodb.net/?retryWrites=true&w=majority
spring.data.mongodb.database=customer-api

# Launching url will look like http://localhost:8080/customer-api/swagger-ui.html
