server.port=8080
spring.application.name=customer-api

# swagger
springdoc.swagger-ui.path=/customer-api/swagger-ui.html

# Launching url will look like http://localhost:8080/customer-api/swagger-ui.html
