spring.application.name=customer-api

server.port= 8080

#swagger URI
springdoc.swagger-ui.path=/customer-api/swagger-ui.html

spring.data.mongodb.uri=mongodb+srv://TestUser:test123@mytraining.ztbwtzg.mongodb.net/?retryWrites=true&w=majority&appName=MyTraining
spring.data.mongodb.database=AccTrainingDb

#http://localhost:8080/customer-api/swagger-ui.html
