openapi: '3.0.2'

info:
  title: Customer API
  version: '1.0'
  contact:
    name: Accenture Training
    email: contact@example.com
    url: http:example.com
    
servers:
  - url: http://localhost:8080

tags:
  - name: Customer API

paths:
  /customer:
    post:
      description: Create Customer
      summary: create customer for given request
      tags:
        - "Customer API"
      operationId: createCustomer
      requestBody:
        description: create customer in database
        content:
          application/json:
            schema: 
              $ref: '#/components/schemas/Customer'

      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Customer'
        '500':
            description: Internal Sever Error
  /customer/{id}:
    get:
      operationId: getCustomer
      summary: Fetch customer details for given id
      tags:
        - "Customer API"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad request
        '404':
          description: Not Found
        '500':
          description: Interal Server Error

components:
  schemas:
    Customer: 
     description: This is a customer model/schema
     type: object
     required:
       - "customerId"
     properties:
       customerId:
        type: string
        description: Id of the customer
        example: 12345
        minLength: 5
        maxLength: 8
       customerName:
        type: string
        example: Rahul Anand
        description: First Name and Last Name of the customer
       customerAddress:
        type: string
        example: Hartford, CT
       officeCode:
        type: number
        example: 075
