openapi: '3.0.2'

info:
  title: Customer API
  version: '1.0'
  contact:
    name: Accenture Training
    email: ashwathy.poonath@accenture.com
    url: http://example.com

servers:
  - url: http://localhost:8080

paths:
  /customer:
    post:
      description: Create Customer
      summary: Create Customer for given request
      operationId: createCustomer
      requestBody:
        description: Create Customer in Database
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '500':
          description: Internal Server Error        

  /customer/{id}:
    get:
      operationId: getCustomer
      summary: Fetch customer details
      tags:
        - "Customer API"
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Customer'
        '400':
          description: Bad request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

components:
  schemas:
    Customer:
      description: This is Customer Schema/Model
      type: object
      required:
        - 'customerId'
      properties:
        customerId:
          type: string
          description: ID of the Customer
          example: 12345
          minLength: 5
          maxLength: 8
        customerName:
          type: string
          example: Ashwathy Poonath
          description: First Name and Last Name of the Customer
        customerAddress:
          type: string
          example: India
        officeCode:
          type: integer
          example: 045